version: '3.4'

services:
  picpaysimplificado.webapi:
    image: ${DOCKER_REGISTRY-}picpaysimplificadowebapi
    build:
      context: .
      dockerfile: src/Services/APIs/PicPaySimplificado.WebApi/Dockerfile
    depends_on:
        - picpaysimplificado.db
        - picpaysimplificado.rabbitmq
    restart: on-failure
    ports:
        - 8080:80
    networks:
        - picpaysimplificado-network

  picpaysimplificado.transactionconsumer:
    image: ${DOCKER_REGISTRY-}picpaysimplificadotransactionconsumer
    build:
      context: .
      dockerfile: src/Services/QeueConsumers/PicPaySimplificado.TransactionConsumer/Dockerfile
    depends_on:
        - picpaysimplificado.mongo
        - picpaysimplificado.rabbitmq
    restart: on-failure
    ports:
        - 4450:80
    networks:
        - picpaysimplificado-network


  picpaysimplificado.userconsumer:
    image: ${DOCKER_REGISTRY-}picpaysimplificadouserconsumer
    build:
      context: .
      dockerfile: src/Services/QeueConsumers/PicPaySimplificado.UserConsumer/Dockerfile
    depends_on:
        - picpaysimplificado.mongo
        - picpaysimplificado.rabbitmq
    restart: on-failure
    ports:
        - 4440:80
    networks:
        - picpaysimplificado-network

  picpaysimplificado.mongo:
    container_name: picpay.simplificado-nosql-db
    image: mongo
    restart: on-failure
    ports:
        - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    networks:
        - picpaysimplificado-network

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-container
    links:
        -  picpaysimplificado.mongo
    ports:
        - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
        - picpaysimplificado.mongo
    networks:
        - picpaysimplificado-network

  picpaysimplificado.rabbitmq:
    container_name: picpay.simplificado-broker
    image: masstransit/rabbitmq
    hostname: picpaysimplificado.queue
    ports:
        - 15672:15672
        - 5672:5672
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    networks:
        - picpaysimplificado-network

  picpaysimplificado.db:
    container_name: picpay.simplificado-db
    image: mcr.microsoft.com/mssql/server
    ports:
       - 1433:1433
    environment:
        SA_PASSWORD: 1q2w3e4r@#$
        ACCEPT_EULA: "Y"
    restart: on-failure
    networks:
        - picpaysimplificado-network
  
networks:
    picpaysimplificado-network:
        driver: bridge


